# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0002_datavalidationrule_source_kind_and_more'),
        ('device_manager', '0002_device_assigned_line_device_certificate_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128)),
                ('scope', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('output_uri', models.TextField(blank=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('target_type', models.CharField(max_length=32)),
                ('retention_days', models.PositiveIntegerField()),
                ('archive_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('compression_enabled', models.BooleanField(default=False)),
                ('rules_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('edge_to_cloud', 'Edge to Cloud'), ('cloud_to_edge', 'Cloud to Edge')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('payload_ref', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sync_type'], name='storage_syn_sync_ty_84c515_idx'), models.Index(fields=['status'], name='storage_syn_status_4b3215_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('raw', 'Raw'), ('processed', 'Processed'), ('result', 'Result'), ('evidence', 'Evidence'), ('model', 'Model'), ('report', 'Report')], max_length=16)),
                ('file_uri', models.TextField()),
                ('storage_tier', models.CharField(default='local', max_length=32)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_artifacts', to='device_manager.device')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_artifacts', to='data_ingestion.sample')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artifact_type'], name='storage_syn_artifac_ecf55c_idx'), models.Index(fields=['storage_tier'], name='storage_syn_storage_0df917_idx')],
            },
        ),
    ]
