# Generated by Django 6.0.3 on 2026-03-25 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=128)),
                ('metric_name', models.CharField(max_length=128)),
                ('metric_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['component'], name='monitoring__compone_cb46b5_idx'), models.Index(fields=['metric_name'], name='monitoring__metric__292cf7_idx'), models.Index(fields=['captured_at'], name='monitoring__capture_86baaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=16)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['component'], name='monitoring__compone_4ff2b4_idx'), models.Index(fields=['severity'], name='monitoring__severit_f709e2_idx'), models.Index(fields=['created_at'], name='monitoring__created_b295e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['service_name'], name='monitoring__service_cabf9b_idx'), models.Index(fields=['status'], name='monitoring__status_a405b2_idx'), models.Index(fields=['checked_at'], name='monitoring__checked_bfb02e_idx')],
            },
        ),
    ]
