# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_datavalidationrule_source_kind_and_more'),
        ('device_manager', '0002_device_assigned_line_device_certificate_status_and_more'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_service', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('root_cause_hint', models.TextField(blank=True)),
                ('impacted_services', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_cases', to='device_manager.device')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_cases', to='data_ingestion.sample')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['source_service'], name='monitoring__source__9fea34_idx'), models.Index(fields=['severity'], name='monitoring__severit_39cb54_idx'), models.Index(fields=['status'], name='monitoring__status_690cb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_utc', models.DateTimeField()),
                ('cpu_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('battery_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('health_state', models.CharField(blank=True, max_length=32)),
                ('telemetry_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='device_manager.device')),
            ],
            options={
                'ordering': ['-timestamp_utc'],
                'indexes': [models.Index(fields=['timestamp_utc'], name='monitoring__timesta_d34c08_idx'), models.Index(fields=['health_state'], name='monitoring__health__aef66c_idx')],
            },
        ),
    ]
