# Generated by Django 6.0.3 on 2026-04-01 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_device_assigned_line_device_certificate_status_and_more'),
        ('monitoring', '0002_incidentcase_telemetryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHealthSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(blank=True, null=True)),
                ('health_score', models.FloatField()),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNRELIABLE', 'Unreliable')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('gating_valid', models.BooleanField(default=True)),
                ('signal_quality', models.FloatField(default=1.0)),
                ('channel_consistency', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_health_summaries', to='device_manager.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIHealthExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('ai_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='monitoring.aihealthsummary')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHealthSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_score', models.FloatField()),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('sampling_integrity', models.FloatField(default=1.0)),
                ('sensor_health', models.FloatField(default=1.0)),
                ('env_stability', models.FloatField(default=1.0)),
                ('connectivity', models.FloatField(default=1.0)),
                ('maintenance', models.FloatField(default=1.0)),
                ('flow_ok', models.BooleanField(default=True)),
                ('fan_ok', models.BooleanField(default=True)),
                ('clog_risk', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_health_summaries', to='device_manager.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aihealthsummary',
            index=models.Index(fields=['device', 'created_at'], name='monitoring__device__98bc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthsummary',
            index=models.Index(fields=['health_status'], name='monitoring__health__4cadd5_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthexplanation',
            index=models.Index(fields=['reason_code'], name='monitoring__reason__09240f_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthexplanation',
            index=models.Index(fields=['severity'], name='monitoring__severit_8a442c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicehealthsummary',
            index=models.Index(fields=['device', 'created_at'], name='monitoring__device__efa8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='devicehealthsummary',
            index=models.Index(fields=['health_status'], name='monitoring__health__60843a_idx'),
        ),
    ]
