# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_orchestration', '0001_initial'),
        ('data_ingestion', '0002_datavalidationrule_source_kind_and_more'),
        ('device_manager', '0002_device_assigned_line_device_certificate_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('channel', models.CharField(choices=[('ui', 'UI'), ('webhook', 'Webhook'), ('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('destination', models.CharField(max_length=255)),
                ('severity_threshold', models.CharField(default='medium', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('rule_type', models.CharField(choices=[('threshold', 'Threshold'), ('anomaly', 'Anomaly'), ('business', 'Business')], max_length=16)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('conditions_json', models.JSONField(blank=True, default=dict)),
                ('actions_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['rule_type'], name='quality_cen_rule_ty_88f320_idx'), models.Index(fields=['is_active'], name='quality_cen_is_acti_f88179_idx')],
            },
        ),
        migrations.CreateModel(
            name='QualityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('freshness_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('quality_index', models.DecimalField(decimal_places=3, max_digits=6)),
                ('risk_band', models.CharField(max_length=32)),
                ('decision', models.CharField(max_length=32)),
                ('recommendation', models.TextField(blank=True)),
                ('score_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_scores', to='ai_orchestration.inferenceresult')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='data_ingestion.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('hold', 'Hold'), ('reject', 'Reject'), ('override', 'Override')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_reviews', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_reviews', to='data_ingestion.sample')),
                ('quality_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quality_center.qualityscore')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_service', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='device_manager.device')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='data_ingestion.sample')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='quality_center.notificationroute')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity'], name='quality_cen_severit_4386b3_idx'), models.Index(fields=['status'], name='quality_cen_status_f9bb15_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='qualityscore',
            index=models.Index(fields=['risk_band'], name='quality_cen_risk_ba_8a7afb_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityscore',
            index=models.Index(fields=['decision'], name='quality_cen_decisio_8f8740_idx'),
        ),
    ]
