# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0002_datavalidationrule_source_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(max_length=64)),
                ('feature_json', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(max_length=32)),
                ('health_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vectors', to='data_ingestion.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=128)),
                ('model_type', models.CharField(choices=[('sensing', 'Sensing'), ('vision', 'Vision'), ('fusion', 'Fusion')], max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('runtime_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('canary', 'Canary'), ('archived', 'Archived')], default='inactive', max_length=16)),
                ('artifact_uri', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_name', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('model_name', 'version'), name='unique_model_name_version')],
            },
        ),
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('feature_vector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_jobs', to='ai_orchestration.featurevector')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_jobs', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='data_ingestion.sample')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='ai_orchestration.modelartifact')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='PreprocessingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=128, unique=True)),
                ('modality', models.CharField(choices=[('signal', 'Signal'), ('image', 'Image'), ('fusion', 'Fusion')], max_length=16)),
                ('target_domain', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile_name'],
                'indexes': [models.Index(fields=['modality'], name='ai_orchestr_modalit_e16096_idx'), models.Index(fields=['is_active'], name='ai_orchestr_is_acti_eaa5af_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processed_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preprocessing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_records', to='ai_orchestration.preprocessingprofile')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_records', to='data_ingestion.sample')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_records', to='data_ingestion.collectionsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='featurevector',
            name='processed_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_vectors', to='ai_orchestration.processedrecord'),
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('risk_band', models.CharField(blank=True, max_length=32)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_orchestration.inferencejob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['result_type'], name='ai_orchestr_result__2cc442_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['job_type'], name='ai_orchestr_job_typ_4db9dd_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['status'], name='ai_orchestr_status_fee635_idx'),
        ),
        migrations.AddIndex(
            model_name='processedrecord',
            index=models.Index(fields=['created_at'], name='ai_orchestr_created_e45b49_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevector',
            index=models.Index(fields=['feature_type'], name='ai_orchestr_feature_3aa530_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevector',
            index=models.Index(fields=['version'], name='ai_orchestr_version_0a00e4_idx'),
        ),
    ]
