# Generated by Django 6.0.3 on 2026-03-25 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('device_type', models.CharField(max_length=64)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('retired', 'Retired')], default='registered', max_length=16)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['external_id'], name='device_mana_externa_c9365f_idx'), models.Index(fields=['status'], name='device_mana_status_1bdb42_idx'), models.Index(fields=['device_type'], name='device_mana_device__06f05a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('registered', 'Registered'), ('provisioned', 'Provisioned'), ('heartbeat', 'Heartbeat'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], max_length=32)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('retired', 'Retired')], max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='device_manager.device')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['event_type'], name='device_mana_event_t_406acb_idx'), models.Index(fields=['status'], name='device_mana_status_951fb2_idx'), models.Index(fields=['recorded_at'], name='device_mana_recorde_7ffa1c_idx')],
            },
        ),
    ]
