# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_line',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='device',
            name='certificate_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='configuration_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='connectivity_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioned', 'Provisioned'), ('revoked', 'Revoked')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('paused', 'Paused'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='registered', max_length=16),
        ),
        migrations.AlterField(
            model_name='devicelifecycleevent',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('paused', 'Paused'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], max_length=16),
        ),
        migrations.CreateModel(
            name='DeviceChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_code', models.CharField(max_length=64)),
                ('channel_name', models.CharField(max_length=128)),
                ('sensor_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('faulted', 'Faulted')], default='active', max_length=16)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='device_manager.device')),
            ],
            options={
                'ordering': ['device__name', 'channel_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_version', models.CharField(max_length=64)),
                ('sampling_rate_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('trigger_rules', models.JSONField(blank=True, default=dict)),
                ('sensors_enabled', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='device_manager.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmwareUpdateJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_jobs', to='device_manager.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_code', models.CharField(max_length=64, unique=True)),
                ('site_name', models.CharField(max_length=128)),
                ('location_name', models.CharField(blank=True, max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_name'],
                'indexes': [models.Index(fields=['site_code'], name='device_mana_site_co_5e8d8b_idx'), models.Index(fields=['site_name'], name='device_mana_site_na_df1f47_idx')],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='device_manager.site'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['assigned_line'], name='device_mana_assigne_5451a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicechannel',
            constraint=models.UniqueConstraint(fields=('device', 'channel_code'), name='unique_device_channel_code'),
        ),
        migrations.AddConstraint(
            model_name='deviceconfiguration',
            constraint=models.UniqueConstraint(fields=('device', 'config_version'), name='unique_device_config_version'),
        ),
        migrations.AddIndex(
            model_name='firmwareupdatejob',
            index=models.Index(fields=['status'], name='device_mana_status_1fb359_idx'),
        ),
        migrations.AddIndex(
            model_name='firmwareupdatejob',
            index=models.Index(fields=['target_version'], name='device_mana_target__91397c_idx'),
        ),
    ]
