# Generated by Django 6.0.3 on 2026-03-25 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=64)),
                ('schema_version', models.CharField(default='1.0', max_length=32)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sensor_type', '-updated_at'],
                'indexes': [models.Index(fields=['sensor_type'], name='data_ingest_sensor__2a4e55_idx'), models.Index(fields=['is_active'], name='data_ingest_is_acti_420452_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ingest_source', models.CharField(default='api', max_length=32)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='pending', max_length=16)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='device_manager.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sensor_type'], name='data_ingest_sensor__4a9398_idx'), models.Index(fields=['validation_status'], name='data_ingest_validat_a20081_idx'), models.Index(fields=['created_at'], name='data_ingest_created_10e651_idx')],
            },
        ),
    ]
