# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
        ('device_manager', '0002_device_assigned_line_device_certificate_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalidationrule',
            name='source_kind',
            field=models.CharField(default='sensor', max_length=32),
        ),
        migrations.AddField(
            model_name='datavalidationrule',
            name='transform_hints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='quality_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('product_name', models.CharField(max_length=128)),
                ('supplier_name', models.CharField(blank=True, max_length=128)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch_code'], name='data_ingest_batch_c_540bc5_idx'), models.Index(fields=['product_name'], name='data_ingest_product_e56dd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalibrationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=128, unique=True)),
                ('sensor_type', models.CharField(max_length=64)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('effective_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['profile_name'],
                'indexes': [models.Index(fields=['sensor_type'], name='data_ingest_sensor__1c7bb3_idx'), models.Index(fields=['is_active'], name='data_ingest_is_acti_b0c1b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=16)),
                ('sampling_strategy', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='data_ingestion.batch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sessions', to='device_manager.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_readings', to='data_ingestion.collectionsession'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_code', models.CharField(max_length=64, unique=True)),
                ('collected_at', models.DateTimeField()),
                ('sample_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='data_ingestion.batch')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='device_manager.device')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='device_manager.site')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=64)),
                ('file_uri', models.TextField()),
                ('captured_at', models.DateTimeField()),
                ('image_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='device_manager.device')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='data_ingestion.collectionsession')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='data_ingestion.sample')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionsession',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='data_ingestion.sample'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_readings', to='data_ingestion.sample'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_code', models.CharField(max_length=64, unique=True)),
                ('sensor_type', models.CharField(max_length=64)),
                ('sensor_model', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='device_manager.device')),
            ],
            options={
                'ordering': ['sensor_code'],
            },
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='data_ingestion.sensor'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['sample_code'], name='data_ingest_sample__dd4b29_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['collected_at'], name='data_ingest_collect_b46331_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecapture',
            index=models.Index(fields=['camera_id'], name='data_ingest_camera__fcaa68_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecapture',
            index=models.Index(fields=['captured_at'], name='data_ingest_capture_50f1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsession',
            index=models.Index(fields=['session_code'], name='data_ingest_session_107013_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsession',
            index=models.Index(fields=['status'], name='data_ingest_status_02afd2_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['sensor_type'], name='data_ingest_sensor__984ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['sensor_code'], name='data_ingest_sensor__3a14ed_idx'),
        ),
    ]
