export const fallbackOverview = {
  total_sites: 4,
  total_devices: 28,
  active_devices: 24,
  active_protocol_adapters: 7,
  active_sessions: 5,
  queued_inference_jobs: 14,
  open_alerts: 6,
  pending_sync_jobs: 9,
  pending_approvals: 3,
  unhealthy_services: 2,
};

export const fallbackBlueprint = {
  brand: "MxSense Adaptive Intelligence Systems",
  modules: [
    {
      slug: "dashboard",
      title: "Dashboard",
      summary: "Single-pane operational view for runtime health, quality, alerts, and sync continuity.",
      subTabs: [
        "Fleet Summary",
        "Quality Summary",
        "Runtime Summary",
        "Sync Status",
        "Alerts",
      ],
      focusTab: "Fleet Summary",
      panelTitle: "Open the site-wide command center first.",
      panelBullets: [
        "Review active devices, active sessions, and running jobs.",
        "Watch quality indicators, pass or fail patterns, and risk shifts.",
        "Track Jetson runtime health across CPU, GPU, memory, and storage.",
        "Move from alert to evidence with one drill-down path.",
      ],
      quickStats: ["Devices Online", "Jobs Running", "Quality Index"],
      interfaces: ["REST", "WebSocket", "Metrics"],
      backendServices: ["api-gateway", "monitoring", "quality-center"],
    },
    {
      slug: "device-management",
      title: "Device Management",
      summary: "Manage connected sensing devices across onboarding, provisioning, firmware, and live state.",
      subTabs: [
        "Registration",
        "Update",
        "Remove",
        "Pause",
        "Provisioning",
        "Assignment",
        "Firmware",
        "Status",
        "Configuration",
      ],
      focusTab: "Registration",
      panelTitle: "Registration workflow",
      panelBullets: [],
      subTabPanels: {
        Registration: {
          title: "Registration workflow",
          bullets: [],
        },
        Update: {
          title: "Update device metadata",
          bullets: [],
        },
        Remove: {
          title: "Remove / decommission device",
          bullets: [],
        },
        Pause: {
          title: "Pause device participation",
          bullets: [],
        },
        Provisioning: {
          title: "Provisioning",
          bullets: [],
        },
        Assignment: {
          title: "Assignment",
          bullets: [],
        },
        Firmware: {
          title: "Firmware",
          bullets: [],
        },
        Status: {
          title: "Status",
          bullets: [],
        },
        Configuration: {
          title: "Configuration",
          bullets: [],
        },
      },
      subTabActions: {
        Registration: ["Add device", "Assign device ID", "Map device type", "Start onboarding"],
        Update: [
          "Edit metadata",
          "Update location",
          "Assign channels",
          "Set firmware reference",
          "Set calibration profile",
          "Assign Camera",
        ],
        Remove: ["Decommission", "Revoke credentials", "Archive history", "Remove Camera"],
        Pause: ["Pause communication", "Pause ingestion", "Pause inference", "Resume device"],
        Provisioning: ["Assign token", "Issue certificate", "Bind MQTT topics", "Set API permissions"],
        Assignment: ["Link to site", "Assign production line", "Set batch workflow", "Set product category"],
        Firmware: ["Assign OTA package", "Track version", "Check update status", "Schedule update"],
        Status: ["Refresh status", "Mark maintenance mode", "Acknowledge fault", "View history"],
        Configuration: ["Set sampling rate", "Enable/disable sensors", "Set thresholds", "Edit trigger rules"],
      },
      actionForms: {
        "add-device": {
          subTab: "Registration",
          title: "Add New Device",
          description: "Register a new sensing device and create the initial device record.",
          fields: [
            { name: "deviceName", label: "Device name", type: "text", placeholder: "device_001", required: true },
            { name: "deviceType", label: "Device type", type: "text", placeholder: "Jetson-NX / SensorHub / ...", required: true },
            { name: "location", label: "Location", type: "text", placeholder: "Factory-Line-A", required: true },
          ],
        },
        "assign-device-id": {
          subTab: "Registration",
          title: "Assign Device ID",
          description: "Assign a persistent device ID to an existing device record.",
          fields: [
            { name: "deviceName", label: "Device name", type: "text", placeholder: "device_001", required: true },
            { name: "deviceId", label: "New device ID", type: "text", placeholder: "MXD-000123", required: true },
          ],
        },
        "map-device-type": {
          subTab: "Registration",
          title: "Map Device Type",
          description: "Map the physical device type to the platform device schema.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "deviceType", label: "Schema device type", type: "text", placeholder: "sensor-module-v2", required: true },
          ],
        },
        "start-onboarding": {
          subTab: "Registration",
          title: "Start Onboarding",
          description: "Trigger the onboarding workflow for device registration completion.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "workflow", label: "Onboarding workflow", type: "text", placeholder: "default-onboarding", required: false },
          ],
        },

        "edit-metadata": {
          subTab: "Update",
          title: "Edit Metadata",
          description: "Update device metadata fields used by governance and orchestration.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "metadataKey", label: "Metadata key", type: "text", placeholder: "displayName / notes / modelTag", required: true },
            { name: "metadataValue", label: "Metadata value", type: "text", placeholder: "Device A - Line 1", required: true },
          ],
        },
        "assign-camera": {
          subTab: "Update",
          title: "Assign Camera",
          description: "Map an ESP32-CAM device IP to this platform device for image capture.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "device_01 / external_id", required: true },
            { name: "ipAddress", label: "ESP32 IP", type: "text", placeholder: "192.168.0.187", required: true },
            { name: "cameraLabel", label: "Camera label (optional)", type: "text", placeholder: "Front Cam", required: false },
            {
              name: "captureIntervalSeconds",
              label: "Auto-capture interval (seconds)",
              type: "number",
              placeholder: "30",
              required: false,
              defaultValue: 30,
            },
          ],
        },
        "update-location": {
          subTab: "Update",
          title: "Update Location",
          description: "Modify the device location used for routing, reporting, and operational context.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "location", label: "New location", type: "text", placeholder: "Lab-Test / Factory-Line-A", required: true },
          ],
        },
        "assign-channels": {
          subTab: "Update",
          title: "Assign Channels",
          description: "Assign/attach communication and data channels to the device.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "channels", label: "Channels (comma-separated)", type: "textarea", placeholder: "mqtt://topic/1, ws://stream/2", required: true },
          ],
        },
        "set-firmware-reference": {
          subTab: "Update",
          title: "Set Firmware Reference",
          description: "Link the device to a firmware reference used for OTA deployment selection.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "firmwareRef", label: "Firmware reference", type: "text", placeholder: "fw-bundle-1.8.2", required: true },
          ],
        },
        "set-calibration-profile": {
          subTab: "Update",
          title: "Set Calibration Profile",
          description: "Attach a calibration profile to the device to normalize sensor outputs.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "calibrationProfile", label: "Calibration profile", type: "text", placeholder: "cal-profile-2026-03", required: true },
          ],
        },

        "decommission": {
          subTab: "Remove",
          title: "Decommission Device",
          description: "Decommission a device and revoke lifecycle permissions.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "reason", label: "Reason", type: "text", placeholder: "Hardware retired / moved / replaced", required: false },
          ],
        },
        "remove-camera": {
          subTab: "Remove",
          title: "Remove Camera",
          description: "Remove the ESP32-CAM mapping so this device stops returning images from S3.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "device_01 / external_id", required: true },
            { name: "reason", label: "Reason (optional)", type: "text", placeholder: "No longer connected / replaced", required: false },
          ],
        },
        "revoke-credentials": {
          subTab: "Remove",
          title: "Revoke Credentials",
          description: "Revoke device credentials to stop authentication and topic access.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "credentialScope", label: "Credential scope", type: "text", placeholder: "mqtt / api / both", required: false },
          ],
        },
        "archive-history": {
          subTab: "Remove",
          title: "Archive Device History",
          description: "Archive the device audit/history evidence for compliance and troubleshooting.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "retention", label: "Archive retention (days)", type: "number", placeholder: "365", required: false },
          ],
        },

        "pause-communication": {
          subTab: "Pause",
          title: "Pause Communication",
          description: "Temporarily disable device communication at the broker/protocol adapter layer.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "until", label: "Pause until (ISO timestamp)", type: "text", placeholder: "2026-03-28T10:00:00Z", required: false },
          ],
        },
        "pause-ingestion": {
          subTab: "Pause",
          title: "Pause Ingestion",
          description: "Stop ingesting device data into processing pipelines while leaving connectivity intact.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "until", label: "Pause until (ISO timestamp)", type: "text", placeholder: "2026-03-28T10:00:00Z", required: false },
          ],
        },
        "pause-inference": {
          subTab: "Pause",
          title: "Pause Inference",
          description: "Hold inference participation for the device while maintaining collection/config.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "until", label: "Pause until (ISO timestamp)", type: "text", placeholder: "2026-03-28T10:00:00Z", required: false },
          ],
        },
        "resume-device": {
          subTab: "Pause",
          title: "Resume Device",
          description: "Resume the device to normal operations after a pause/fault hold.",
          fields: [{ name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true }],
        },

        "assign-token": {
          subTab: "Provisioning",
          title: "Assign Token",
          description: "Assign an access token used by the device to authenticate.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "token", label: "Token value", type: "text", placeholder: "eyJhbGciOi...", required: true },
          ],
        },
        "issue-certificate": {
          subTab: "Provisioning",
          title: "Issue Certificate",
          description: "Provision/issue a certificate for secure device communication.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "certificateId", label: "Certificate ID", type: "text", placeholder: "cert-2026-03-001", required: false },
          ],
        },
        "bind-mqtt-topics": {
          subTab: "Provisioning",
          title: "Bind MQTT Topics",
          description: "Bind allowed MQTT topics to the device for ingestion and telemetry.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "mqttTopics", label: "MQTT topics (comma-separated)", type: "textarea", placeholder: "site/a/#, site/b/telemetry", required: true },
          ],
        },
        "set-api-permissions": {
          subTab: "Provisioning",
          title: "Set API Permissions",
          description: "Set API permissions used by the device for governed operations.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "permissions", label: "Permissions (comma-separated)", type: "textarea", placeholder: "ingest:read, ingest:write", required: true },
          ],
        },

        "link-to-site": {
          subTab: "Assignment",
          title: "Link to Site",
          description: "Link the device to a specific site for routing and reporting.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "site", label: "Site", type: "text", placeholder: "Site A / plant_01", required: true },
          ],
        },
        "assign-production-line": {
          subTab: "Assignment",
          title: "Assign Production Line",
          description: "Assign the device to a production line or operational batch grouping.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "productionLine", label: "Production line", type: "text", placeholder: "Line 2 / L-14", required: true },
          ],
        },
        "set-batch-workflow": {
          subTab: "Assignment",
          title: "Set Batch Workflow",
          description: "Select which batch workflow the device participates in.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "batchWorkflow", label: "Batch workflow", type: "text", placeholder: "batch-workflow-v3", required: true },
          ],
        },
        "set-product-category": {
          subTab: "Assignment",
          title: "Set Product Category",
          description: "Set the product category context used by quality and inference pipelines.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "productCategory", label: "Product category", type: "text", placeholder: "Fruits / Oils / Industrial", required: true },
          ],
        },

        "assign-ota-package": {
          subTab: "Firmware",
          title: "Assign OTA Package",
          description: "Assign an OTA firmware package to the device for update execution.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "otaPackage", label: "OTA package", type: "text", placeholder: "fw-ota-1.8.2", required: true },
          ],
        },
        "track-version": {
          subTab: "Firmware",
          title: "Track Firmware Version",
          description: "Set which firmware version the device should report/track.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "targetVersion", label: "Target version", type: "text", placeholder: "1.8.2", required: false },
          ],
        },
        "check-update-status": {
          subTab: "Firmware",
          title: "Check Update Status",
          description: "Query the current firmware update state for the device.",
          fields: [{ name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true }],
        },
        "schedule-update": {
          subTab: "Firmware",
          title: "Schedule Firmware Update",
          description: "Schedule a firmware update at a given time window.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "scheduleTime", label: "Schedule time (ISO timestamp)", type: "text", placeholder: "2026-03-28T10:00:00Z", required: true },
          ],
        },

        "refresh-status": {
          subTab: "Status",
          title: "Refresh Device Status",
          description: "Refresh online/offline and operational status for the device.",
          fields: [{ name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true }],
        },
        "mark-maintenance-mode": {
          subTab: "Status",
          title: "Mark Maintenance Mode",
          description: "Enter/exit maintenance mode and affect operational participation.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "enabledUntil", label: "Enabled until (ISO timestamp)", type: "text", placeholder: "2026-03-28T18:00:00Z", required: false },
          ],
        },
        "acknowledge-fault": {
          subTab: "Status",
          title: "Acknowledge Fault",
          description: "Acknowledge a fault and update fault state in the operational timeline.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "faultId", label: "Fault ID", type: "text", placeholder: "fault-2026-03-001", required: false },
          ],
        },
        "view-history": {
          subTab: "Status",
          title: "View Device History",
          description: "View recent events, state transitions, and operational records.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "range", label: "History range", type: "text", placeholder: "last-24h / last-7d", required: false },
          ],
        },

        "set-sampling-rate": {
          subTab: "Configuration",
          title: "Set Sampling Rate",
          description: "Configure device sampling frequency for sensor readings.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "samplingRate", label: "Sampling rate (Hz)", type: "number", placeholder: "10", required: true },
          ],
        },
        "enable-disable-sensors": {
          subTab: "Configuration",
          title: "Enable/Disable Sensors",
          description: "Enable or disable sensors for this device.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "sensors", label: "Sensors (comma-separated)", type: "textarea", placeholder: "env/voc, env/pm, audio/distance", required: true },
            {
              name: "enabled",
              label: "Set state",
              type: "select",
              options: [
                { value: "true", label: "Enable" },
                { value: "false", label: "Disable" },
              ],
              required: true,
            },
          ],
        },
        "set-thresholds": {
          subTab: "Configuration",
          title: "Set Thresholds",
          description: "Configure trigger thresholds for sensor values.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "thresholdsJson", label: "Thresholds (JSON)", type: "textarea", placeholder: '{"env.temp": {"min":0,"max":100}}', required: true },
          ],
        },
        "edit-trigger-rules": {
          subTab: "Configuration",
          title: "Edit Trigger Rules",
          description: "Edit trigger rules that decide when alerts/inference triggers occur.",
          fields: [
            { name: "deviceId", label: "Device ID", type: "text", placeholder: "MXD-000123", required: true },
            { name: "rulesJson", label: "Rules (JSON)", type: "textarea", placeholder: '{"when":"pm2_5>25","action":"alert"}', required: true },
          ],
        },
      },
      quickStats: ["Total Devices", "Offline Devices", "Firmware Pending"],
      interfaces: ["REST", "MQTT"],
      backendServices: ["device-manager", "governance", "mqtt-service"],
    },
    {
      slug: "adaptation",
      title: "Adaptation",
      summary: "Normalize MQTT, RTSP, Modbus, serial, and API sources into platform-ready payloads.",
      subTabs: ["MQTT", "API", "Protocol Adapters", "Data Sources", "Input Mapping"],
      focusTab: "MQTT",
      panelTitle: "Connectivity setup",
      panelBullets: [
        "Map topics and bindings before enabling collection.",
        "Validate endpoint health and QoS behavior.",
        "Normalize industrial payloads into the platform schema.",
        "Keep source testing inside the same operator workspace.",
      ],
      quickStats: ["Active Topics", "Adapter Errors", "Mapped Sources"],
      interfaces: ["MQTT", "REST", "RTSP", "Serial"],
      backendServices: ["mqtt-service", "data-ingestion", "api-gateway"],
    },
    {
      slug: "data",
      title: "Data",
      summary: "Run collection sessions, manage sampling, batch context, aggregation, and fusion-ready records.",
      subTabs: ["Ingestion", "Collection", "Sampling", "Aggregation", "Fusion"],
      focusTab: "Collection",
      panelTitle: "Collection control",
      panelBullets: [
        "Start and stop live collection sessions safely.",
        "Bind sample, batch, operator, and site context to each run.",
        "Watch stream latency, packet rate, and missing data signals.",
        "Prepare records for downstream preprocessing and inference.",
      ],
      quickStats: ["Active Sessions", "Packet Rate", "Dropped Packets"],
      interfaces: ["REST", "MQTT", "WebSocket"],
      backendServices: ["data-ingestion", "device-manager", "monitoring"],
    },
    {
      slug: "preprocessing-engine",
      title: "Preprocessing Engine",
      summary: "Clean, align, and transform multimodal inputs into trusted feature-ready records.",
      subTabs: [
        "Signal Cleaning",
        "Smoothing",
        "Normalization",
        "Windowing",
        "Feature Extraction",
      ],
      focusTab: "Signal Cleaning",
      panelTitle: "Trust-building preprocessing",
      panelBullets: [
        "Compare raw and processed signals side by side.",
        "Handle drift, missing values, outliers, and temporal alignment.",
        "Apply reusable profiles for spices, fruits, oils, air, or industrial use.",
        "Generate stable vectors before inference is triggered.",
      ],
      quickStats: ["Signal Quality", "Drift Risk", "Feature Count"],
      interfaces: ["Internal APIs", "REST", "File API"],
      backendServices: ["ai-orchestration", "data-ingestion"],
    },
    {
      slug: "inferencing",
      title: "Inferencing",
      summary: "Run sensing, vision, and fusion models locally on the edge runtime.",
      subTabs: [
        "Vision Service",
        "Sensing Service",
        "Fusion Inference",
        "Model Runtime",
        "Result Review",
      ],
      focusTab: "Sensing Service",
      panelTitle: "Edge inference runtime",
      panelBullets: [
        "Queue or auto-trigger inference on prepared samples.",
        "Compare model versions with confidence and uncertainty in one place.",
        "Review pass, hold, reject, grade, and risk outputs together.",
        "Support human-in-loop review for borderline results.",
      ],
      quickStats: ["Active Model", "Queued Jobs", "Confidence Trend"],
      interfaces: ["REST", "gRPC", "Local Runtime"],
      backendServices: ["ai-orchestration", "quality-center"],
    },
    {
      slug: "performance",
      title: "Performance",
      summary: "Observe alerts, logs, latency, throughput, and infrastructure efficiency.",
      subTabs: ["Alerts", "Notifications", "Logging", "Throughput", "Latency"],
      focusTab: "Alerts",
      panelTitle: "Operational performance view",
      panelBullets: [
        "Surface high-priority incidents before the operator sees noise.",
        "Track ingestion, preprocessing, inference, and API response latency.",
        "Monitor queue depth and runtime bottlenecks continuously.",
        "Link failures to logs, alerts, and resource pressure.",
      ],
      quickStats: ["Open Alerts", "Queue Depth", "GPU Utilization"],
      interfaces: ["REST", "Metrics", "WebSocket"],
      backendServices: ["monitoring", "quality-center", "api-gateway"],
    },
    {
      slug: "api-gateway",
      title: "API Gateway",
      summary: "Expose governed REST and stream interfaces for frontend and enterprise consumers.",
      subTabs: ["Usage", "Inputs", "Outputs", "API Registry", "Routing"],
      focusTab: "API Registry",
      panelTitle: "Integration surface",
      panelBullets: [
        "Browse documented endpoints inside the console.",
        "Track request logs, endpoint health, and client usage.",
        "Separate device inputs, user inputs, outputs, and stream channels clearly.",
        "Keep developer workflows inside governed access boundaries.",
      ],
      quickStats: ["API Volume", "Endpoint Health", "Connected Clients"],
      interfaces: ["REST", "WebSocket", "JWT"],
      backendServices: ["api-gateway", "governance"],
    },
    {
      slug: "controls",
      title: "Controls",
      summary: "Handle policy, security, approvals, and operational control actions in one governed area.",
      subTabs: ["Users & Roles", "Policies", "Security", "Approvals", "Change Mgmt"],
      focusTab: "Users & Roles",
      panelTitle: "Governed control plane",
      panelBullets: [
        "Manage role access, policy changes, and secret rotation.",
        "Approve model, config, and device lifecycle changes deliberately.",
        "Preserve audit evidence for every governed action.",
        "Keep control workflows separate from daily operator tasks.",
      ],
      quickStats: ["Active Users", "Pending Approvals", "Policy Changes"],
      interfaces: ["REST", "Audit APIs"],
      backendServices: ["governance", "device-manager", "storage-sync"],
    },
    {
      slug: "monitoring-agent",
      title: "Monitoring Agent",
      summary: "Track device health, service health, data health, AI health, and incident context.",
      subTabs: [
        "Device Health",
        "Data Health",
        "Inference Health",
        "Service Health",
        "Incident View",
      ],
      focusTab: "Service Health",
      panelTitle: "Health and incident drill-down",
      panelBullets: [
        "Inspect device heartbeat, telemetry, and power state.",
        "See service dependencies and restart pressure in one map.",
        "Track drift, failed jobs, and confidence degradation early.",
        "Move from incident headline to root-cause hints quickly.",
      ],
      quickStats: ["Healthy Services", "Incidents", "Sync Backlog"],
      interfaces: ["REST", "Metrics", "Logs"],
      backendServices: ["monitoring", "quality-center", "storage-sync"],
    },
    {
      slug: "edge-ai-health",
      title: "Edge AI Health",
      summary: "Decision reliability monitoring (confidence, gating, and channel consistency).",
      subTabs: ["Overview"],
      focusTab: "Overview",
      panelTitle: "Edge AI health monitoring",
      panelBullets: [],
      quickStats: ["Health Score", "Confidence", "Gating Valid"],
      interfaces: ["REST"],
      backendServices: ["monitoring", "ai-orchestration"],
    },
    {
      slug: "device-health",
      title: "Device Health",
      summary: "Hardware reliability monitoring (flow, fan, connectivity, maintenance).",
      subTabs: ["Overview"],
      focusTab: "Overview",
      panelTitle: "Device health monitoring",
      panelBullets: [],
      quickStats: ["Health Score", "Flow OK", "Fan OK"],
      interfaces: ["REST"],
      backendServices: ["monitoring", "device-manager"],
    },
    {
      slug: "storage-management",
      title: "Storage Management",
      summary: "Control local raw, processed, feature, evidence, and backup data lifecycles.",
      subTabs: [
        "Raw Storage",
        "Processed Storage",
        "Feature Store",
        "Results Store",
        "Backup",
      ],
      focusTab: "Raw Storage",
      panelTitle: "Retention and evidence handling",
      panelBullets: [
        "Store original records, transformed outputs, features, and results cleanly.",
        "Control retention, archival, compression, and restore jobs.",
        "Keep evidence export available for QA and compliance review.",
        "Protect the edge node from uncontrolled storage growth.",
      ],
      quickStats: ["Storage Used", "Archive Ready", "Last Backup"],
      interfaces: ["REST", "File API"],
      backendServices: ["storage-sync", "data-ingestion", "ai-orchestration"],
    },
  ],
  services: [
    { name: "device-manager", responsibility: "registry, provisioning, configuration, firmware, lifecycle" },
    { name: "data-ingestion", responsibility: "sessions, samples, raw readings, image capture, validation" },
    { name: "mqtt-service", responsibility: "protocol adapters, topic routing, schema mappings, message logs" },
    { name: "ai-orchestration", responsibility: "preprocessing, features, model registry, inference jobs and results" },
    { name: "quality-center", responsibility: "quality scoring, rules, alerts, decision review" },
    { name: "monitoring", responsibility: "telemetry, service health, metrics, logs, incidents" },
    { name: "storage-sync", responsibility: "artifacts, retention, backup, edge-to-cloud sync" },
    { name: "governance", responsibility: "roles, policies, approvals, secrets, audit" },
    { name: "api-gateway", responsibility: "overview, registry, request logs, frontend blueprint surface" },
  ],
};

export function getModuleBySlug(slug) {
  return fallbackBlueprint.modules.find((module) => module.slug === slug);
}
