# Generated by Django 6.0.3 on 2026-03-25 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('topic_pattern', models.CharField(max_length=255, unique=True)),
                ('qos', models.PositiveSmallIntegerField(default=0)),
                ('parser_name', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('retain_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['topic_pattern'], name='mqtt_servic_topic_p_c4fdb9_idx'), models.Index(fields=['is_active'], name='mqtt_servic_is_acti_5d9d0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MqttMessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('qos', models.PositiveSmallIntegerField(default=0)),
                ('retain', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processing_notes', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mqtt_messages', to='device_manager.device')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mqtt_service.topicsubscription')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['topic'], name='mqtt_servic_topic_4929ad_idx'), models.Index(fields=['processed'], name='mqtt_servic_process_45f110_idx'), models.Index(fields=['received_at'], name='mqtt_servic_receive_2429b3_idx')],
            },
        ),
    ]
