# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolAdapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('adapter_type', models.CharField(choices=[('mqtt', 'MQTT'), ('rtsp', 'RTSP'), ('modbus', 'Modbus'), ('serial', 'Serial'), ('api', 'API')], max_length=16)),
                ('endpoint', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['adapter_type'], name='mqtt_servic_adapter_bd1016_idx'), models.Index(fields=['status'], name='mqtt_servic_status_99c395_idx')],
            },
        ),
        migrations.AddField(
            model_name='topicsubscription',
            name='adapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_subscriptions', to='mqtt_service.protocoladapter'),
        ),
        migrations.CreateModel(
            name='SchemaMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_field', models.CharField(max_length=128)),
                ('target_field', models.CharField(max_length=128)),
                ('transform_rule', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_mappings', to='mqtt_service.protocoladapter')),
            ],
            options={
                'ordering': ['adapter__name', 'source_field'],
                'constraints': [models.UniqueConstraint(fields=('adapter', 'source_field', 'target_field'), name='unique_schema_mapping')],
            },
        ),
    ]
