# Generated by Django 6.0.3 on 2026-03-25 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('client_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('mobile', 'Mobile'), ('operations', 'Operations')], max_length=32)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=32)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['client_type'], name='api_gateway_client__30b4d9_idx'), models.Index(fields=['is_active'], name='api_gateway_is_acti_2e1b7b_idx')],
            },
        ),
    ]
