# Generated by Django 6.0.3 on 2026-03-25 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendclient',
            name='module_access',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=16)),
                ('service_domain', models.CharField(max_length=64)),
                ('auth_required', models.BooleanField(default=True)),
                ('websocket_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['service_domain', 'path'],
                'indexes': [models.Index(fields=['service_domain'], name='api_gateway_service_7592f0_idx'), models.Index(fields=['method'], name='api_gateway_method_7d3071_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=16)),
                ('status_code', models.PositiveIntegerField()),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('response_size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api_gateway.frontendclient')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api_gateway.apiendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status_code'], name='api_gateway_status__414401_idx'), models.Index(fields=['created_at'], name='api_gateway_created_23384e_idx')],
            },
        ),
    ]
